// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {

  static FirebaseOptions get currentPlatform {

    if (kIsWeb) {
      return web;

    }

    switch (defaultTargetPlatform) {

      case TargetPlatform.android:
        return android;

      case TargetPlatform.iOS:
        return ios;

      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',

        );

      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',

        );

      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );

      default:

        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );

    }

  }



  static const FirebaseOptions android = FirebaseOptions(

    apiKey: 'AIzaSyAunuLX3l7myKOli9ZMKiIIRLzElq_lV84',
    appId: '1:888787405219:android:01d3a80341e092bfa83216',
    messagingSenderId: '888787405219',
    projectId: 'doctorappointmentapp-a87fd',
    storageBucket: 'doctorappointmentapp-a87fd.firebasestorage.app',

  );



  static const FirebaseOptions web = FirebaseOptions(

    apiKey: 'AIzaSyBrrtSu28sVp76_jfePbtWD6z-mKibEVRA',
    appId: '1:888787405219:web:20ae7b7a42de5885a83216',
    messagingSenderId: '888787405219',
    projectId: 'doctorappointmentapp-a87fd',
    authDomain: 'doctorappointmentapp-a87fd.firebaseapp.com',
    storageBucket: 'doctorappointmentapp-a87fd.firebasestorage.app',

  );



  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2NGbOuYNTGpkMh83LjoVyQgBh8I9WC0E',
    appId: '1:888787405219:ios:7874dc9d3106b074a83216',
    messagingSenderId: '888787405219',
    projectId: 'doctorappointmentapp-a87fd',
    storageBucket: 'doctorappointmentapp-a87fd.firebasestorage.app',
    iosBundleId: 'com.example.practica',

  );



}